language: go

go:
  - 1.9.x
  - stable
  - master

matrix:
  # Failing on the development version of Go isn't too bad.
  allow_failures:
    - go: master

script:
  - go test -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
